export const MAX_DOMAINS = 5;
export const PUBLIC_DOMAIN = process.env.NEXT_PUBLIC_DOMAIN || "llamadns.org";
export const API_DOMAIN = `www.${PUBLIC_DOMAIN}`;

export const RESERVED_SUBDOMAINS = new Set([
  "www",
  "mail",
  "smtp",
  "pop",
  "imap",
  "ftp",
  "ns",
  "ns1",
  "ns2",
  "dns",
  "api",
  "app",
  "admin",
  "dashboard",
  "login",
  "auth",
  "status",
  "blog",
  "docs",
  "help",
  "support",
  "cdn",
  "static",
  "assets",
  "dev",
  "staging",
  "test",
  "demo",
  "mx",
  "autoconfig",
  "autodiscover",
  "_dmarc",
  "_domainkey",
]);
